services:
  mariadb:
    image: mariadb
    volumes:
      - moodle-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=moodle
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  moodle:
    image: bitnami/moodle:latest
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
      - PUID=1000
      - PGID=1000
    volumes:
      - moodle:/bitnami/moodle
      - moodle-data:/bitnami/moodledata
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  moodle:
    external: true
  moodle-data:
    external: true
  moodle-database:
    external: true