---
- name: Create VM Templates for Ubuntu 22.04 (Jammy Jellyfish)
  hosts: discovery
  become: true
  ignore_errors: yes # set right now until I can fix the download_cloud_init role

  roles:
    # Download cloud-init images
    - download_cloud_init_images
    # Clone Cloud-init to VM's   ***To be completed***
    - clone_cloud_init_images 

- name: Install Docker and inject docker files for ELK Stack
  remote_user: justin
  hosts: docker-siem
  become: true
  roles:
    - provision_docker_server
    - docker-compose-inject