---
- name: Download Cloud Init Images and Clone VMs on Home Servers
  hosts: servers-all # Change to match hosts file
  become: true

  roles:
    - role: download_cloud_init_images  #Comment out if Cloud Init Images exist
    # Clone Cloud-init to VM's, duplicate for each VM
    - role: clone_cloud_init_images 
      proxmox_user: root@pam # Change as neccessary
      proxmox_password: #Please use a secret manager
      proxmox_host: # Change as neccessary 
      proxmox_node: # Change as neccessary
      ip_address: 'dhcp'
      proxmox_storage: # Change as Necessary
      proxmox_image: ubuntu-2204-cloud #this should match the image name in the first role above
      hard_drive_space: 100G
      gateway: 172.16.10.1 #change this to match your network
      mem: 16384
      cpu: 2
      vm_name: development.home.initcyber.com
      vm_new_id: 100
      ssh_key: 

    - role: clone_cloud_init_images 
      proxmox_user: root@pam
      proxmox_password: Please use a secret manager
      proxmox_host: # Change as neccessary
      proxmox_node: # Change as neccessary
      ip_address: 'dhcp'
      proxmox_storage: Intel-1TB-ZE1P0B
      proxmox_image: ubuntu-2204-cloud
      hard_drive_space: 10G
      gateway: 172.16.10.1 #change this to match your network
      mem: 8192
      cpu: 2
      vm_name: devops.home.initcyber.com
      vm_new_id: 101
      ssh_key: 
      
    - role: clone_cloud_init_images 
      proxmox_user: root@pam
      proxmox_password: Please use a secret manager
      proxmox_host: discovery
      proxmox_node: discovery
      ip_address: 'dhcp'
      proxmox_storage: Intel-1TB-ZE1P0B
      proxmox_image: ubuntu-2204-cloud
      hard_drive_space: 10G
      gateway: 172.16.10.1 #change this to match your network
      mem: 8192
      cpu: 2
      vm_name: deploy.home.inticyber.com
      vm_new_id: 102
      ssh_key: 

- name: Download Cloud Init Images and Clone VMs on Enterprise
  hosts: enterprise # Change to match hosts file
  become: true
    - role: clone_cloud_init_images 
      proxmox_user: root@pam
      proxmox_password: Please use a secret manager
      proxmox_host: enterprise
      proxmox_node: enterprise
      ip_address: 'dhcp'
      proxmox_storage: Intel-1TB-ZE1P0B
      proxmox_image: ubuntu-2204-cloud
      hard_drive_space: 10G
      gateway: 172.16.10.1 #change this to match your network
      mem: 8192
      cpu: 2
      vm_name: splunk
      vm_new_id: 500
      ssh_key: 

    - role: clone_cloud_init_images 
      proxmox_user: root@pam
      proxmox_password: Please use a secret manager
      proxmox_host: enterprise
      proxmox_node: enterprise
      ip_address: 'dhcp'
      proxmox_storage: Intel-1TB-ZE1P0B
      proxmox_image: ubuntu-2204-cloud
      hard_drive_space: 10G
      gateway: 172.16.10.1 #change this to match your network
      mem: 8192
      cpu: 2
      vm_name: wazuh
      vm_new_id: 501
      ssh_key: 