---
- name: Create VM Templates for Ubuntu 22.04 (Jammy Jellyfish)
  hosts: discovery # Change to match hosts file
  become: true
#  ignore_errors: yes # set right now until I can fix the download_cloud_init role

  roles:
    #- role: download_cloud_init_images  #Comment out if Cloud Init Images exist
    # Clone Cloud-init to VM's, duplicate for each VM
    - role: clone_cloud_init_images 
      proxmox_user: root@pam
      proxmox_password: Please use a secret manager
      proxmox_host: discovery
      proxmox_node: discovery
      ip_address: 'dhcp'
      proxmox_storage: Intel-1TB-ZE1P0B
      proxmox_image: ubuntu-2204-cloud
      hard_drive_space: 10G
      gateway: 172.16.10.1 #change this to match your network
      mem: 16384
      cpu: 2
      vm_name: test50
      vm_new_id: 104
      ssh_key:

- name: Install Docker and inject docker files for Continuous Integration Stack
  remote_user: justin
  hosts: devdocker # Change to match hosts file
  become: true
  roles:
    - provision_docker_server