version: "3.8"

services:

  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "3002:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://172.16.100.10:11434' 
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-local:/app/backend/data


volumes:
  open-webui-local:
    external: true
  
