# Install dependencies (Pytest)
- name: Install dependencies for Pytest
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - python3-pip

########################################################################################################################
# Install Git Hub Runner (Self Hosted)
# To be integrated
########################################################################################################################

########################################################################################################################
# Install Semgrep
########################################################################################################################
- name: Install semgrep
  pip:
    name: semgrep

########################################################################################################################
# FROM HERE YOU NEED TO RUN DIRECTLY ON THE VM
# semgrep login
########################################################################################################################


########################################################################################################################
# Install OWASP ZAP
# To be integrated
########################################################################################################################

########################################################################################################################
# Install Falco
########################################################################################################################

- name:  Add an apt signing key for Falco
  ansible.builtin.shell:
    cmd: curl -fsSL https://falco.org/repo/falcosecurity-packages.asc |  sudo gpg --dearmor -o /usr/share/keyrings/falco-archive-keyring.gpg


- name: Add repo for Falco
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/falco-archive-keyring.gpg] https://download.falco.org/packages/deb stable main"
    state: present


- name: Install dependencies for Falco and Install Falco
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - dkms 
      - make 
      - linux-headers-$(uname -r)
      - llvm
      - falco
           
