# Install dependencies (Pytest)
- name: Install dependencies for Pytest
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - python3-pip


- name: Install pytest
  pip:
    name: pytest
########################################################################################################################
## Install Trivy
# Incorporate GH Action here : https://github.com/aquasecurity/trivy-action and https://github.com/aquasecurity/trivy-sarif-demo/blob/master/.github/workflows/scan.yml
########################################################################################################################
- name: Install dependencies for Trivy
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - wget
      - apt-transport-https
      - gnupg
      - lsb-release

- name: Add an apt signing key for Trivy
  become: true
  apt_key:
    url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    state: present
- name: Add apt repository for stable version Trivy
  become: true
  apt_repository:
    repo: deb https://aquasecurity.github.io/trivy-repo/deb jammy main
    filename: trivy
    state: present

- name: Install Trivy
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - trivy

########################################################################################################################
# Install Semgrep
########################################################################################################################
- name: Install semgrep
  pip:
    name: semgrep

########################################################################################################################
# FROM HERE YOU NEED TO RUN DIRECTLY ON THE VM
# semgrep login
########################################################################################################################


########################################################################################################################
# Install Falco
########################################################################################################################

- name:  Add an apt signing key for Falco
  ansible.builtin.shell:
    cmd: curl -fsSL https://falco.org/repo/falcosecurity-packages.asc |  sudo gpg --dearmor -o /usr/share/keyrings/falco-archive-keyring.gpg


- name: Add repo for Falco
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/falco-archive-keyring.gpg] https://download.falco.org/packages/deb stable main"
    state: present


- name: Install dependencies for Falco and Install Falco
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - dkms 
      - make 
      - linux-headers-$(uname -r)
      - llvm
      - falco
           
