# UPGRADE AND INSTALL REQUIRED UBUNTU PACKAGES
- name: Perform an update/dist upgrade
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools

# DOCKER INSTALLATION
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

  #Change arch=***** to amd64 for x86 or arm64 for arm based (pi or arm processors)
- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

- name: Add user to docker group
  user:
    name: "{{ansible_user}}"
    group: docker

# Download Docker-Compose
- name: Install Docker Compose
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker-compose-plugin

# REQUIRED PACKAGES FOR USING ANSIBLE DOCKER (for portainer installation below)
- name: Install related Ubuntu packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - python3-pip
      - mc

- name: Install python packages
  pip:
    name: docker


# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module
#- name: Create portainer container
#  docker_container:
#    name: portainer
#    image: portainer/portainer-ce
#    state: started
#    recreate: yes
#    restart_policy: always
#    published_ports:
#      - "8000:8000"
#      - "9000:9000"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data


# FIREWALL SETUP - If Needed - Commented out for now
#- name: Open Portainer port
#  ufw:
#    state: enabled
#    rule: allow
#    port: "9000"
#    proto: tcp

#- name: Open SSH port
#  ufw:
#    state: enabled
#    rule: allow
#    port: "22"
#    proto: tcp