---

# migrate PG version with pg_upgradecluster (see manpage)
postgresql_version: "14"
postgresql_initidb_path: "/usr/lib/postgresql/{{postgresql_version}}/bin/initdb"
postgresql_config_path: "/etc/postgresql/{{postgresql_version}}/main/postgresql.conf"
postgresql_data_dir: "/var/lib/postgresql/{{postgresql_version}}/main"
postgresql_apt_packages:
  - "postgresql-{{postgresql_version}}"
  - "pgcli"
  - "postgresql-client"
  - "postgresql-common"
