version: "3.8"

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:2.11.3' #https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3824
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npmdata:/data
      - letsencrypt:/etc/letsencrypt

  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "3000:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://172.16.10.80:11434' 
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-local:/app/backend/data

  node_exporter: #Monitors Oracle Cloud system
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    ports:
    - 9100:9100
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave' #This is READ ONLY

  cadvisor: #Monitors Docker Containers
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    restart: unless-stopped
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379

volumes:
  open-webui-local:
    external: true
  npmdata:
    external: true
  letsencrypt:
    external: true
  
