---
services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    env_file: .env
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=America/New_York
      - TITLE=Ubuntu #optional
      - CUSTOM_USER=justin
    volumes:
      - /home/justin/webtop:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000 #http
      - 3001:3001 # https
    shm_size: "4gb" #optional
    restart: unless-stopped
    #Testing out WebTop Container - Last update 1/19/2024
