# Following https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html
- name: Adjust mmap count for Wazuh
  become: yes
  shell:
    cmd: "sysctl -w vm.max_map_count=262144"

# Check to see if Docker Wazuh already exists in directory
- name: Check to see if Docker Wazuh directory exists
  remote_user: justin  #Change to your user as needed #######
  stat:
    path: ~/wazuh-docker
  register: wazuhdir

- debug:
    msg: "Wazuh Directory already exists!"
  when: wazuhdir.stat.exists
- debug:
    msg: "File not found, downloading now:"
  when: not wazuhdir.stat.exists

# Download latest Wazuh Docker from github
- name: Clone Wazuh Github Repo (If it doesn't exist)
  shell:
    cmd: cd ~ && git clone https://github.com/wazuh/wazuh-docker.git -b v4.7.2
  when: not wazuhdir.stat.exists

- name: Wazuh Self Sign Certs
  remote_user: justin  #Change to your user as needed #######
  shell:
    cmd: "cd ~/wazuh-docker/single-node && docker compose -f generate-indexer-certs.yml run --rm generator"

- name: Run Wazuh Docker Container
  remote_user: justin  #Change to your user as needed #######
  shell:
    cmd: "cd ~/wazuh-docker/single-node && docker compose up -d"


#########################################################################
#Default UN and PW for Wazuh: admin / SecretPassword (https://hostname) #
#Default UN and PW for Kibana: kibanaserver/kibanaserver                #
#########################################################################



- name: Create Splunk container
  remote_user: justin  #Change to your user as needed #######
  docker_container:
    name: splunk
    image: splunk/splunk:latest
    state: started
    recreate: yes
    restart_policy: always
    published_ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - splunk_logs:/data ### Note: Need to add Network Share!
    env:
      SPLUNK_START_ARGS: '--accept-license' 
      SPLUNK_PASSWORD: '<secret password>'

###########################################################################################
#Default UN and PW for Splunk: admin / (Whatever your password is) (http://hostname:8000) #
###########################################################################################