on:
  schedule:
    - cron:  '15 00 * * *'
  workflow_dispatch:
    inputs:

name: Upload Logs to SIEM
jobs:
  logs-download:
    name: Download GH action logs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Download Logs
        uses: pawanbahuguna/action-logs/@v1.0.1
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ONLY_24: true # Default is true [Optional]
          LOGS_DIR: jobs-log # Default is jobs-log [Optional]
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          
##### Uncomment below to push jobs-logs to Github Interface (in the run)

#      - uses: actions/upload-artifact@v4
#        with:
#          name: workflow-logs
#          path: jobs-log/*


      - name: Upload Logs
        uses: appleboy/scp-action@master
        with:
          username: justin
          host: ${{ secrets.SIEMHOST }}
          key: ${{ secrets.SSH_justin }}
          source: jobs-log/
          target: '/home/justin/logs/'
 #         strip_components: 3

  #from here: https://github.com/marketplace/actions/github-action-logs
