vars: 
  proxmox_user: Please
  proxmox_password: use
  proxmox_host: some
  proxmox_node: sort
  ip_address: 192.168.1.x
  proxmox_storage: local-zfs
  proxmox_image: ubuntu-2204-cloud
  hard_drive_space: 50G #this increased by 50 gigabytes
  gateway: 192.168.1.x
  mem: 16384 #In bytes
  cpu: 2
  vm_name: test50
  vm_new_id: 104 #vm ID of new clone


#Install required packages
- name: Install required packages
  apt:
    name:
      - python3-pip
      - python3-dev
      - build-essential
      - libguestfs-tools
      - virtualenv
      - python3-proxmoxer
      - python3-requests

- name: Clone Cloud-Init Image
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_user}}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_host }}"
    clone: ubuntu-2204-cloud
    name: "{{ vm_name }}"
    node: "{{ proxmox_node }}"
    storage: "{{ proxmox_storage }}" #Change to match storage name
    format: qcow2
    timeout: 500
    ide:
      ide2: 'local-zfs:vm-9999-cloudinit'
    net:
      net0: 'virtio,bridge=vmbr0,tag=10'
    ipconfig:
      ipconfig0: 'ip=172.16.10.81/24'
    newid: "{{ vm_new_id }}"
    sshkeys: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILJkVm98B71lD5XHfihwcYHE9TVpsJmK1vR1JcaU82L+'
    searchdomains: 'home.initcyber.com'

- name: Update VM configuration
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_host }}"
    name: "{{ vm_name }}"
    node: "{{ proxmox_node }}"
    cores: "{{ cpu }}"
    memory: "{{ mem }}"
    scsi: 
      scsi0: '{{ proxmox_storage }}:+50G'
    update: true

# I literally can't find an ansible way to do this outside of shell
- name: Grow Disk
  ansible.builtin.shell:
    cmd: qm resize "{{ vm_new_id }}" scsi0 "+{{ hard_drive_space }}"



  

