version : '3.8'
 
services:
  postgres:
    container_name: openrmf-postgres
    image: postgres:11.16
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_DB=keycloak 
      - POSTGRES_USER=keycloak 
      - POSTGRES_PASSWORD=password
    networks:
      - keycloak-network

  keycloak: 
    container_name: openrmf-keycloak
    image: jboss/keycloak:15.0.0
    restart: always
    ports:
      - 9001:8080
    environment:
      - KEYCLOAK_USER=admin 
      - KEYCLOAK_PASSWORD=admin 
      - DB_VENDOR=postgres
      - DB_ADDR=postgres 
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak 
      - DB_PASSWORD=password
      - PROXY_ADDRESS_FORWARDING=true
    depends_on:
      - postgres
    volumes:
      - /private/var/services/keycloak/themes/openrmf/:/opt/jboss/keycloak/themes/openrmf/:ro
      - /private/var/services/keycloak/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml:ro
    networks:
      - keycloak-network


networks:
  keycloak-network: