name: Mirror to Public Repository

on:
  push:
    branches:
      - main  # Specify branch to track in the private repository
  schedule:
    - cron: '0 * * * *'  # Adjust the schedule as needed (e.g., runs every hour)

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Private Repo
      uses: actions/checkout@v2
      with:
        repository: initcyber/homelab_priv
        token: ${{ secrets.TOKEN }}  # Use PAT with read access to the private repository

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Clone Public Repo
      run: |
        git clone --single-branch --branch main https://github.com/initcyber/homelab.git public_repo

    - name: Sync Repositories
      run: |
        rsync -av --delete --exclude '.git' --exclude '.github/workflows/sync_to_public.yml' ./ public_repo/

    - name: Commit and Push Changes
      run: |
        cd public_repo
        git add --all
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          last_commit_message=$(git -C ../ log -1 --pretty=%B)
          git commit -m "$last_commit_message"
          git push https://${{ secrets.TOKEN }}@github.com/initcyber/homelab.git main