name: Mirror to Public Repository

on:
  push:
    branches:
      - main  # Specify branch to track in the private repository
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight, adjust as needed

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Private Repo
      uses: actions/checkout@v2
      with:
        repository: initcyber/homelab_priv
        token: ${{ secrets.TOKEN }}  # Use PAT with read access to the private repository

    - name: Clone Public Repo
      run: |
        # Setup git
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        
        # Clone the public repository into the 'public_repo' directory
        git clone --single-branch --branch main https://github.com/initcyber/homelab.git public_repo

    - name: Sync Repositories
      run: |
        # Sync contents from the private repo (current directory) to the public_repo directory
        rsync -av --delete --exclude '.git' --exclude '.github' ./ public_repo/

    - name: Commit and Push Changes
      run: |
        cd public_repo

        # Add all changes
        git add --all
        
        # Check for changes
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          # Get the last commit message from the private repository
          last_commit_message=$(git log -1 --pretty=%B)
          
          # Commit changes using the same message
          git commit -m "$last_commit_message"

          # Push changes to the public repository
          git push https://${{ secrets.TOKEN }}@github.com/initcyber/homelab.git main