name: Mirror to Public Repository

on:
  push:
    branches:
      - main  # or your default branch name
  workflow_dispatch:  # Allows manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to public repository
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:initcyber/homelab_priv.git"
          destination-repo: "git@github.com:initcyber/homelab.git"
