name: Sync to Public Repository

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to repository
        uses: tech-thinker/push-to-repo@v1.0.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          user-name: "github-actions[bot]"
          user-email: "github-actions[bot]@users.noreply.github.com"
          source-directory: "."  # The directory containing files to push
          destination-github-username: "initcyber"
          destination-repository-name: "homelab"
          target-branch: main